# Generated by Django 4.2.4 on 2023-09-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
